StartupEvents.registry('block', event => {
    
  event.create("raw_diamond_block")
    .displayName("钻石原石块")
    .hardness(3.0)
    .stoneSoundType()
    .tagBlock('tconstruct:mineable/pickadze')
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('forge:mineable/paxel')
    .tagBlock('forge:storage_blocks')
    .tagBlock('forge:storage_blocks/raw_diamond')
    .tagBlock('minecraft:needs_iron_tool')

  event.create("raw_emerald_block")
    .displayName("绿宝石原石块")
    .hardness(3.0)
    .stoneSoundType()
    .tagBlock('tconstruct:mineable/pickadze')
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('forge:mineable/paxel')
    .tagBlock('forge:storage_blocks')
    .tagBlock('forge:storage_blocks/raw_emerald')
    .tagBlock('minecraft:needs_iron_tool')

  event.create("raw_redstone_block")
    .displayName("红石原石块")
    .hardness(2.0)
    .stoneSoundType()
    .tagBlock('tconstruct:mineable/pickadze')
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('forge:mineable/paxel')
    .tagBlock('forge:storage_blocks')
    .tagBlock('forge:storage_blocks/raw_redstone')
    .tagBlock('minecraft:needs_iron_tool')

  })